# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /source
RUN dotnet new -i Amazon.Lambda.Templates

# copy csproj and restore as distinct layers
# COPY *.csproj .
# RUN dotnet restore